config/routes.rb
Rails.application.routes.draw do
 
  resources :relations

mount Judge::Engine => '/judge'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  devise_scope :users do
     get '/users/auth/:action/callback' => 'users/omniauth_callbacks#passthru'
    get 'register', to: 'devise/registrations#new', as: :register
  end

  resources :users do
    get :my_user, :on => :collection
  end 
  resources :posts
  root to: "posts#index"
  

end

app/models/relation.rb
class Relation < ActiveRecord::Base
	belongs_to :user
	belongs_to :relation , class_name: 'User'
	
	def self.denied
		where{status.matches "denied"}
	end
	
	def self.request
		where{status.matches "request"}
	end
	
	def self.accept
		where{status.matches "accept"}
	end
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  before_action :set_relation, only: [:show, :edit, :update, :destroy]

  # GET /relations
  # GET /relations.json
  def index
    @relations = Relation.all
  end

  # GET /relations/1
  # GET /relations/1.json
  def show
  end

  # GET /relations/new
  def new
    @relation = Relation.new
    @users = User.where.not(id: current_user.id)
    my_relations = current_user.relation
    @my_users = []
    my_relations.each do |r|
      @my_users.push(r.relation)
    end
    @users = @users - @my_users
  end

  # GET /relations/1/edit
  def edit
  end

  # POST /relations
  # POST /relations.json
  def create
    @relation = Relation.new(relation_params)

    respond_to do |format|
      if @relation.save
        format.html { redirect_to @relation, notice: 'Relation was successfully created.' }
        format.json { render :show, status: :created, location: @relation }
      else
        format.html { render :new }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relations/1
  # PATCH/PUT /relations/1.json
  def update
    respond_to do |format|
      if @relation.update(relation_params)
        format.html { redirect_to @relation, notice: 'Relation was successfully updated.' }
        format.json { render :show, status: :ok, location: @relation }
      else
        format.html { render :edit }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relations/1
  # DELETE /relations/1.json
  def destroy
    @relation.destroy
    respond_to do |format|
      format.html { redirect_to relations_url, notice: 'Relation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relation
      @relation = Relation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relation_params
      params.required(:data).permit(:user_id, :status, :relation_id)
    end
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/views/relations/_form.html.slim
- @users.each do |u| 
   p=u.username
   =button_to 'Add friend', action: :create, :data => {user_id: current_user.id, relation_id: u.id, status: :request}, form: :relation
   hr

app/views/relations/edit.html.slim
h1 Editing relation
= render 'form'
= link_to 'Show', @relation

= link_to 'Back', relations_path

app/views/relations/index.html.slim
h1 Listing relations
= link_to 'Add friend', new_relation_path, class: "btn btn-primary"
hr
- @relations.each do |relation|
  p
    strong= relation.relation.username
    = link_to 'Remove friend', relation, :method=>'delete', data: {:confirm => "Are you sure?"}, class: "btn btn-primary"
    hr

app/views/relations/new.html.slim
h1 New relation
= render 'form'
= link_to 'Back', relations_path

app/views/relations/show.html.slim
p#notice= notice
= link_to 'Edit', edit_relation_path(@relation)

= link_to 'Back', relations_path