config/routes.rb
Rails.application.routes.draw do
 
  resources :relations

mount Judge::Engine => '/judge'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  devise_scope :users do
     get '/users/auth/:action/callback' => 'users/omniauth_callbacks#passthru'
    get 'register', to: 'devise/registrations#new', as: :register
  end

  resources :users do
    get :my_user, :on => :collection
  end 
  resources :posts
  root to: "posts#index"
  

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.brand{:href => "#"} Blog
          %ul.nav.pull-right
            - if user_signed_in?
              %li
                = image_tag("nouser.jpg")
                = current_user.username
              %li
                %a= link_to('Sign out',:destroy_user_session	)
            - else
              %li
                = link_to('Sign_in',:new_user_session)
              %li
                = link_to('Twitter login',user_omniauth_authorize_path(:twitter))  
              %li
                = link_to('Facebook login',user_omniauth_authorize_path(:facebook))  
              %li
                = link_to('Register',:new_user_session)
    .container
      %p.notice= notice
      %p.alert= alert
      = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title Blog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          a.brand href="#"  Blog
          ul.nav.pull-right
            - if user_signed_in?
              li
                = image_tag("nouser.jpg")
                = current_user.username
              li
                = link_to 'Posts', posts_path
              li
                = link_to 'Friends', relations_path
              li 
                = link_to 'Settings', '#'    
              li
                = link_to('Sign out',:destroy_user_session	)
            - else
              li
                = link_to('Sign_in',:new_user_session)
              li
                = link_to('Twitter login',user_omniauth_authorize_path(:twitter))
              li
                = link_to('Facebook login',user_omniauth_authorize_path(:facebook))
              li
                = link_to('Register',:new_user_session)
    .container
      p.notice= notice
      p.alert= alert
      = yield